config/routes.rb
Rails.application.routes.draw do
  
  get 'login', to: 'users#login'
  get 'logout', to: 'users#logout'
  post 'validate_login', to: 'users#validate_login'
  
  post 'add_classroom_notification', to: 'teachers#add_classroom_notification'
  post 'send_from_teacher_to_parent', to: 'teachers#send_from_teacher_to_parent'
  post 'send_from_parent_to_teacher', to: 'parents#send_from_parent_to_teacher'
  
  get "pages/index"
  get "pages/about"
  get "pages/contact"
  get "pages/features"
  get "pages/login"
  get "pages/pricing"
  get "pages/register"

  resources :users

  resources :student_results

  resources :exams

  resources :teacher_to_parent_notifications

  resources :parent_to_teacher_notifications

  resources :classroom_notifications

  resources :school_notifications

  resources :teachers do
    member do
      get 'students'
      get 'parent'
      post 'approve'
    end
  end

  resources :parents

  resources :students

  resources :classrooms

  resources :schools do
    member do
     post 'approve'
    end
  end
  

  root :to => "users#root"
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :school
end

app/models/exam.rb
class Exam < ActiveRecord::Base
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  belongs_to :student
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/school_notification.rb
class SchoolNotification < ActiveRecord::Base
  belongs_to :school
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :classroom
end

app/models/student_result.rb
class StudentResult < ActiveRecord::Base
  belongs_to :exam
  belongs_to :student
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :classroom
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:name, :date)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_classrooms_table.html.erb
<table class="classrooms_table">
	<thead>
		<th>Standard</th>
		<th>Division</th>
		<th>Action</th>
	</thead>
	<tbody>
	<% classrooms.each do | n | %>
		<tr>
			<td><%=n.standard%></td>
			<td><%=n.division%></td>
			<td><%= link_to 'Delete', n, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<%end%>
	<tbody>
<table>

app/views/shared/_notification_table.html.erb
<table class="notification_table">
	<thead>
		<th>Subject</th>
		<th>Content</th>
		<th>Action</th>
	</thead>
	<tbody>
	<% notifications.each do | n | %>
		<tr>
			<td><%=n.subject%></td>
			<td><%=n.content%></td>
			<%if n.class.name == "SchoolNotification" && session[:role] == "School"%>
				<td><%= link_to 'Delete', school_notification_path(n.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
			<% elsif n.class.name == "ClassroomNotification" && session[:role] == "Teacher"%>
				<td><%= link_to 'Delete', classroom_notification_path(n.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
			<% elsif n.class.name == "ParentToTeacherNotification" && session[:role] == "Teacher"%>
				<td><%= link_to 'Delete', parent_to_teacher_notification_path(n.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
			<% elsif n.class.name == "TeacherToParentNotification" && session[:role] == "Parent"%>
				<td><%= link_to 'Delete', teacher_to_parent_notification_path(n.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
			<%else%>
				<td></td>
			<%end%>
		</tr>
	<%end%>
	<tbody>
<table>

app/views/shared/_pending_table.html.erb
<table class="pending_table">
	<thead>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Action</th>
	</thead>
	<tbody>
	<% pending_list.each do | n | %>
		<tr>
			<td><%= n.first_name%></td>
			<td><%= n.last_name%></td>
			<td>
			<% if model_name == "teachers"%>
			<%= link_to "Approve", approve_teacher_path(n.id), method: :post %>
			<% else %>
			<%= link_to "Approve", approve_parent_path(n.id), method: :post %>
			<% end %>
			</td>
		</tr>
	<%end%>
	<tbody>
<table>
	