config/routes.rb
Rails.application.routes.draw do
  
  get 'login', to: 'users#login'
  get 'logout', to: 'users#logout'
  post 'validate_login', to: 'users#validate_login'
  
  post 'add_classroom_notification', to: 'teachers#add_classroom_notification'
  post 'send_from_teacher_to_parent', to: 'teachers#send_from_teacher_to_parent'
  post 'send_from_parent_to_teacher', to: 'parents#send_from_parent_to_teacher'
  
  get "pages/index"
  get "pages/about"
  get "pages/contact"
  get "pages/features"
  get "pages/login"
  get "pages/pricing"
  get "pages/register"

  resources :users

  resources :student_results

  resources :exams

  resources :teacher_to_parent_notifications

  resources :parent_to_teacher_notifications

  resources :classroom_notifications

  resources :school_notifications

  resources :teachers do
    member do
      get 'students'
      get 'parent'
      post 'approve'
    end
  end

  resources :parents

  resources :students

  resources :classrooms

  resources :schools do
    member do
     post 'approve'
    end
  end
  

  root :to => "users#root"
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :classroom
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    all_students_ids = Student.where(:classroom_id => @teacher.classroom.id).all.pluck(:id)
    @individual_notifications = ParentToTeacherNotification.where(:teacher_id => params[:id]).all
    @school_notifications = SchoolNotification.where(:school_id => @teacher.classroom.school.id).all
    @classroom_notification = ClassroomNotification.where(:classroom_id => @teacher.classroom.id).all
    @pending_parents = Parent.where(:student_id => all_students_ids).where(:is_pending => true).all
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
     @list_of_schools = []
     School.all.each do |school|
       a = []
       a << school.name + ", " + school.city
       a << school.id
       @list_of_schools << a
     end
    @all_classrooms = []
     Classroom.all.each do |classroom|
       a = []
        a << "#{classroom.standard}" + " "+ classroom.division
        a << classroom.id
       @all_classrooms << a
     end
     
  end

  # GET /teachers/1/edit
  def edit
     @list_of_schools = []
     School.all.each do |school|
       a = []
       a << school.name + ", " + school.city
       a << school.id
       @list_of_schools << a
     end
    @all_classrooms = []
     Classroom.all.each do |classroom|
       a = []
        a << "#{classroom.standard}" + " "+ classroom.division
        a << classroom.id
       @all_classrooms << a
     end         
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.is_pending = true 
    respond_to do |format|
      if @teacher.save
        u = User.new(:username => params[:username], :password => params[:password], :role => "Teacher", :identifier=> @teacher.id)
        u.save
        
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def students
    puts "Params in students======"
    teacher_id = params[:id]
    teacher = Teacher.find(teacher_id)
    students = Student.where(:classroom_id => teacher.classroom.id).all
    puts "studentsssss="
    puts students
    @parents=Parent.where(:student_id => students.pluck(:id)).all
    session[:teacher_id] = teacher_id
  end
  
  def parent
    puts "Params =="
    puts params
    @parent = Parent.find(params[:parent_id])
    @teacher = Teacher.find(params[:teacher_id])
  end
  
  def send_from_teacher_to_parent
    p = TeacherToParentNotification.new(:parent_id => params[:parent_id] , :teacher_id => params[:teacher_id] , :subject => params[:subject] , :content => params[:content])
    p.save
    redirect_to teacher_path(params[:teacher_id]) and return
  end
  
  def add_classroom_notification
    n = ClassroomNotification.new(:classroom_id => params[:classroom_id] , :subject => params[:subject] , :content => params[:content])
    n.save
    flash[:notice] = "New Classroom Notification added!"
    redirect_to teacher_path(params[:teacher_id]) and return
  end
  
  def approve
    n = Teacher.find(params[:id])
    n.is_pending = false;
    n.save
    flash[:notice] = "Teacher successfully Approved"
    redirect_to school_path(session[:school_id])
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:classroom_id, :first_name, :last_name, :contact_number, :email_address, :is_pending, :username, :password)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :school_id %><br>
    <%= select_tag :school_id, options_for_select(@list_of_schools) %>
  </div>
  <div class="field">
    <%= f.label :classroom_id %><br>
    <%= f.select :classroom_id, options_for_select(@all_classrooms) %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :contact_number %><br>
    <%= f.text_field :contact_number %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  
  <div class="field">
    <%= label_tag :username %><br>
    <%= text_field_tag :username %>
  </div>
  <div class="field">
    <%= label_tag :password %><br>
    <%= password_field_tag :password %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Classroom</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Contact number</th>
      <th>Email address</th>
      <th>Is pending</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.classroom %></td>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.contact_number %></td>
        <td><%= teacher.email_address %></td>
        <td><%= teacher.is_pending %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/parent.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parent Of:</strong>
  <%= @parent.student.first_name %> <%= @parent.student.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @parent.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @parent.last_name %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @parent.contact_number %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @parent.email_address %>
</p>

<p class="table_heading">Send Notification To Parent</p>
	<%=form_tag(:action => 'send_from_teacher_to_parent') do%>
	<%=hidden_field_tag :parent_id, @parent.id%>
	<%=hidden_field_tag :teacher_id, @teacher.id%>
	<div class="field">
    <%= label_tag :subject %><br>
    <%= text_field_tag :subject %>
  </div>
  <div class="field">
    <%= label_tag :content %><br>
    <%= text_field_tag :content %>
  </div>

  <div class="actions">
    <%= submit_tag "Send Message"%>
  </div>
	<%end%>

</p>

app/views/teachers/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<p>
	<strong>Classroom:</strong>
	<%= @teacher.classroom.standard%> <%= @teacher.classroom.division%>
</p>

<p>
	<strong>First name:</strong>
	<%= @teacher.first_name %>
</p>

<p>
	<strong>Last name:</strong>
	<%= @teacher.last_name %>
</p>

<p>
	<strong>Contact number:</strong>
	<%= @teacher.contact_number %>
</p>

<p>
	<strong>Email address:</strong>
	<%= @teacher.email_address %>
</p>

<p class="table_heading">
	Notifications for the school
</p>
<%= render :partial => "shared/notification_table", :locals => { :notifications => @school_notifications } %>
<br>

<p class="table_heading">
	Notifications for the Class
</p>
Notifications for this school
<%= render :partial => "shared/notification_table", :locals => { :notifications => @classroom_notification } %>
<br>

<p class="table_heading">
	Individual Notifications
</p>
<%= render :partial => "shared/notification_table", :locals => { :notifications => @individual_notifications } %>
<br>

<p class="table_heading">
	Pending Parents Approval List
</p>
<%= render :partial => "shared/pending_table", :locals => { :pending_list => @pending_parents, :model_name => "parents" } %>
<br>

<p class="table_heading">
	Add Message for the class:
</p>
<br>
<div class="border_top">
	<%= form_tag(:action => 'add_classroom_notification',) do %>
	<%= hidden_field_tag :teacher_id, @teacher.id%>
	<%= hidden_field_tag :classroom_id, @teacher.classroom.id%>
	<div class="field">
		<%= label_tag :subject %>
		<br>
		<%= text_field_tag :subject %>
	</div>
	<div class="field">
		<%= label_tag :content %>
		<br>
		<%= text_field_tag :content%>
	</div>

	<div class="actions">
		<%= submit_tag "Add Notification" %>
	</div>
	<% end %>
</div>

<p class="table_heading">List All Students in the class</p>
<%= link_to "List Students",students_teacher_path(@teacher.id)%>
<!-- <%= link_to 'Edit', edit_teacher_path(@teacher) %> -->

app/views/teachers/students.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Link to Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= parent.student.first_name %></td>
        <td><%= parent.student.last_name %></td>
        <td><%= link_to "Parent", parent_teacher_path(:teacher_id => session[:teacher_id], :parent_id => parent.id) %></td>
        <td><%= link_to 'Show', parent.student %></td>        
        <td><%= link_to 'Edit', edit_student_path(parent.student) %></td>
        <td><%= link_to 'Destroy', parent.student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>