config/routes.rb
Rails.application.routes.draw do
  
  get 'login', to: 'users#login'
  get 'logout', to: 'users#logout'
  post 'validate_login', to: 'users#validate_login'
  
  post 'add_classroom_notification', to: 'teachers#add_classroom_notification'
  post 'send_from_teacher_to_parent', to: 'teachers#send_from_teacher_to_parent'
  post 'send_from_parent_to_teacher', to: 'parents#send_from_parent_to_teacher'
  
  get "pages/index"
  get "pages/about"
  get "pages/contact"
  get "pages/features"
  get "pages/login"
  get "pages/pricing"
  get "pages/register"

  resources :users

  resources :student_results

  resources :exams

  resources :teacher_to_parent_notifications

  resources :parent_to_teacher_notifications

  resources :classroom_notifications

  resources :school_notifications

  resources :teachers do
    member do
      get 'students'
      get 'parent'
      post 'approve'
    end
  end

  resources :parents

  resources :students

  resources :classrooms

  resources :schools do
    member do
     post 'approve'
    end
  end
  

  root :to => "users#root"
end

app/models/school_notification.rb
class SchoolNotification < ActiveRecord::Base
  belongs_to :school
end

app/controllers/school_notifications_controller.rb
class SchoolNotificationsController < ApplicationController
  before_action :set_school_notification, only: [:show, :edit, :update, :destroy]

  # GET /school_notifications
  # GET /school_notifications.json
  def index
    @school_notifications = SchoolNotification.all
  end

  # GET /school_notifications/1
  # GET /school_notifications/1.json
  def show
  end

  # GET /school_notifications/new
  def new
    @school_notification = SchoolNotification.new
  end

  # GET /school_notifications/1/edit
  def edit
  end

  # POST /school_notifications
  # POST /school_notifications.json
  def create
    @school_notification = SchoolNotification.new(school_notification_params)

    respond_to do |format|
      if @school_notification.save
        format.html { redirect_to @school_notification, notice: 'School notification was successfully created.' }
        format.json { render :show, status: :created, location: @school_notification }
      else
        format.html { render :new }
        format.json { render json: @school_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /school_notifications/1
  # PATCH/PUT /school_notifications/1.json
  def update
    respond_to do |format|
      if @school_notification.update(school_notification_params)
        format.html { redirect_to @school_notification, notice: 'School notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @school_notification }
      else
        format.html { render :edit }
        format.json { render json: @school_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /school_notifications/1
  # DELETE /school_notifications/1.json
  def destroy
    @school_notification.destroy
    respond_to do |format|
      format.html { redirect_to school_path(session[:school_id]), notice: 'School notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school_notification
      @school_notification = SchoolNotification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_notification_params
      params.require(:school_notification).permit(:school_id, :importance, :subject, :content, :show_until)
    end
end

app/helpers/school_notifications_helper.rb
module SchoolNotificationsHelper
end

app/views/school_notifications/_form.html.erb
<%= form_for(@school_notification) do |f| %>
  <% if @school_notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school_notification.errors.count, "error") %> prohibited this school_notification from being saved:</h2>

      <ul>
      <% @school_notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :school_id %><br>
    <%= f.text_field :school_id %>
  </div>
  <div class="field">
    <%= f.label :importance %><br>
    <%= f.number_field :importance %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :show_until %><br>
    <%= f.date_select :show_until %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/school_notifications/edit.html.erb
<h1>Editing School Notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @school_notification %> |
<%= link_to 'Back', school_notifications_path %>

app/views/school_notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing School Notifications</h1>

<table>
  <thead>
    <tr>
      <th>School</th>
      <th>Importance</th>
      <th>Subject</th>
      <th>Content</th>
      <th>Show until</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @school_notifications.each do |school_notification| %>
      <tr>
        <td><%= school_notification.school %></td>
        <td><%= school_notification.importance %></td>
        <td><%= school_notification.subject %></td>
        <td><%= school_notification.content %></td>
        <td><%= school_notification.show_until %></td>
        <td><%= link_to 'Show', school_notification %></td>
        <td><%= link_to 'Edit', edit_school_notification_path(school_notification) %></td>
        <td><%= link_to 'Destroy', school_notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School notification', new_school_notification_path %>

app/views/school_notifications/new.html.erb
<h1>New School Notification</h1>

<%= render 'form' %>

<%= link_to 'Back', school_notifications_path %>

app/views/school_notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School:</strong>
  <%= @school_notification.school %>
</p>

<p>
  <strong>Importance:</strong>
  <%= @school_notification.importance %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @school_notification.subject %>
</p>

<p>
  <strong>Content:</strong>
  <%= @school_notification.content %>
</p>

<p>
  <strong>Show until:</strong>
  <%= @school_notification.show_until %>
</p>

<%= link_to 'Edit', edit_school_notification_path(@school_notification) %> |
<%= link_to 'Back', school_notifications_path %>